import { Template } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "bd-social-knight",
    name: "Post social — Groupe tes assurances",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Groupe tes\nassurances\net économise.", x: 60, y: 60, fontSize: 80, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 600, lineHeight: 1.05 },
      { type: "cta", id: "cta", label: "En savoir plus", x: 60, y: 540, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 26, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Petit Chevalier", src: "/assets/knight/Heart_01.png", x: 480, y: 450, width: 540, height: 540 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 970, fontSize: 32, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 60, y: 1010, fontSize: 16, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-story-maison",
    name: "Story — Première maison",
    brand: "belairdirect",
    format: "story",
    width: 1080,
    height: 1920,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Première\nmaison?\nFélicitations!\nProchaine\nétape:\nl'assurance!", x: 60, y: 100, fontSize: 96, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 900, lineHeight: 1.0 },
      { type: "cta", id: "cta", label: "En savoir plus", x: 60, y: 1050, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 28, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier maison", src: "/assets/knight/Hold_House_01.png", x: 250, y: 1180, width: 650, height: 550 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 300, y: 1780, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 280, y: 1825, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-habitation",
    name: "Post social — Habitation",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Ton chez-toi.\nBien protégé.\nBien assuré.", x: 60, y: 80, fontSize: 78, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 700, lineHeight: 1.05 },
      { type: "text", id: "body", content: "Assurance habitation à partir de 25$/mois.", x: 60, y: 480, fontSize: 28, fontWeight: "400", color: "rgba(255,255,255,0.8)", fontFamily: "'Roboto', sans-serif" },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 60, y: 570, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 26, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier assis", src: "/assets/knight/Sit_01.png", x: 520, y: 560, width: 500, height: 440 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 970, fontSize: 32, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 60, y: 1010, fontSize: 16, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-story-auto",
    name: "Story — Assurance auto",
    brand: "belairdirect",
    format: "story",
    width: 1080,
    height: 1920,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Ton assurance\nauto,\nsimplifiée.", x: 60, y: 200, fontSize: 96, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 900, lineHeight: 1.0 },
      { type: "text", id: "body", content: "Soumission en 5 min.\nZéro paperasse.", x: 60, y: 750, fontSize: 36, fontWeight: "400", color: "rgba(255,255,255,0.8)", fontFamily: "'Roboto', sans-serif", lineHeight: 1.4 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 60, y: 920, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 32, fontSize: 30, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier auto", src: "/assets/knight/Hold_Car_02_Car_And_House.png", x: 200, y: 1100, width: 700, height: 580 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 300, y: 1780, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 280, y: 1825, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-fier",
    name: "Post social — Chevalier fier",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Économise\njusqu'à 20%\nsur ton\nassurance.", x: 60, y: 60, fontSize: 78, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 650, lineHeight: 1.05 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 60, y: 560, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 26, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier fier", src: "/assets/knight/Proud_01.png", x: 550, y: 500, width: 460, height: 480 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 970, fontSize: 32, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 60, y: 1010, fontSize: 16, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-phone",
    name: "Post social — Mobile",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Gère ton\nassurance\ndepuis\nton cell.", x: 60, y: 60, fontSize: 80, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 600, lineHeight: 1.05 },
      { type: "text", id: "body", content: "Tout dans une app. Simple.", x: 60, y: 500, fontSize: 28, fontWeight: "400", color: "rgba(255,255,255,0.8)", fontFamily: "'Roboto', sans-serif" },
      { type: "cta", id: "cta", label: "Télécharger l'app", x: 60, y: 580, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 26, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier téléphone", src: "/assets/knight/Hold_Phone_01.png", x: 520, y: 480, width: 480, height: 520 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 970, fontSize: 32, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 60, y: 1010, fontSize: 16, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
];
