import { Template } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "bd-social-knight",
    name: "Post social — Petit Chevalier",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Groupe tes assurances\net économise.", x: 60, y: 60, fontSize: 72, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 600, lineHeight: 1.1 },
      { type: "text", id: "body", content: "Plus d'argent pour ta prochaine escapade.", x: 60, y: 340, fontSize: 36, fontWeight: "400", color: "#FFFFFF", fontFamily: "'Roboto', sans-serif", maxWidth: 550 },
      { type: "image", id: "mascot", placeholder: "🛡️ Petit Chevalier", src: "/assets/knight/Heart_01.png", x: 540, y: 420, width: 460, height: 520 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 60, y: 880, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 28, fontFamily: "'Montserrat', sans-serif" },
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 1000, fontSize: 32, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
    ],
  },
  {
    id: "intact-social-habitation",
    name: "Post notoriété — Habitation",
    brand: "intact",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#F7F2EA",
    layers: [
      { type: "text", id: "tagline", content: "Pour tout ce qui compte", x: 60, y: 60, fontSize: 22, fontWeight: "600", color: "#D11338", fontFamily: "Inter, sans-serif" },
      { type: "text", id: "h1", content: "[ Votre chez-vous\nmérite la meilleure\nprotection ]", x: 60, y: 120, fontSize: 68, fontWeight: "700", color: "#000000", fontFamily: "Georgia, serif", maxWidth: 800, lineHeight: 1.15 },
      { type: "image", id: "hero", placeholder: "📸 Photo famille chaleureuse", x: 60, y: 520, width: 960, height: 320, bgColor: "rgba(0,0,0,0.05)" },
      { type: "text", id: "body", content: "Parce que votre maison, c'est bien plus que quatre murs.", x: 60, y: 870, fontSize: 30, fontWeight: "400", color: "#000000", fontFamily: "Inter, sans-serif", maxWidth: 700 },
      { type: "cta", id: "cta", label: "Parler à un courtier", x: 60, y: 960, bgColor: "#D11338", textColor: "#FFFFFF", borderRadius: 28, fontSize: 26, fontFamily: "Inter, sans-serif" },
      { type: "logo", id: "logo", text: "[intact]", x: 830, y: 1010, fontSize: 36, color: "#D11338", fontFamily: "Georgia, serif" },
    ],
  },
  {
    id: "bd-story-auto",
    name: "Story — Assurance auto",
    brand: "belairdirect",
    format: "story",
    width: 1080,
    height: 1920,
    backgroundColor: "#C8102E",
    layers: [
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 80, fontSize: 28, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "h1", content: "Ton assurance\nauto, simplifiée.", x: 60, y: 300, fontSize: 80, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 900, lineHeight: 1.1 },
      { type: "image", id: "mascot", placeholder: "🛡️ Chevalier avec auto", src: "/assets/knight/Hold_Car_02_Car_And_House.png", x: 200, y: 750, width: 680, height: 600 },
      { type: "text", id: "body", content: "Soumission en 5 min.\nZéro paperasse. Zéro détour.", x: 60, y: 1420, fontSize: 40, fontWeight: "400", color: "#FFFFFF", fontFamily: "'Roboto', sans-serif", maxWidth: 800, lineHeight: 1.4 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 60, y: 1620, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 32, fontSize: 32, fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "legal", content: "assurance. simplifiée.", x: 60, y: 1820, fontSize: 22, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "intact-banner-q2",
    name: "Banner — Campagne Q2",
    brand: "intact",
    format: "banner",
    width: 728,
    height: 90,
    backgroundColor: "#F7F2EA",
    layers: [
      { type: "logo", id: "logo", text: "[intact]", x: 16, y: 28, fontSize: 22, color: "#D11338", fontFamily: "Georgia, serif" },
      { type: "text", id: "h1", content: "[ La résilience, c'est dans notre ADN ]", x: 150, y: 20, fontSize: 22, fontWeight: "700", color: "#000000", fontFamily: "Georgia, serif", maxWidth: 380 },
      { type: "text", id: "body", content: "Protégez ce qui compte vraiment.", x: 150, y: 52, fontSize: 14, fontWeight: "400", color: "#000000", fontFamily: "Inter, sans-serif" },
      { type: "cta", id: "cta", label: "En savoir plus", x: 580, y: 24, bgColor: "#D11338", textColor: "#FFFFFF", borderRadius: 20, fontSize: 14, fontFamily: "Inter, sans-serif" },
    ],
  },
  {
    id: "intact-email",
    name: "Email header — Renouvellement",
    brand: "intact",
    format: "email",
    width: 600,
    height: 200,
    backgroundColor: "#F7F2EA",
    layers: [
      { type: "logo", id: "logo", text: "[intact]", x: 24, y: 20, fontSize: 20, color: "#D11338", fontFamily: "Georgia, serif" },
      { type: "text", id: "h1", content: "[ Votre protection continue ]", x: 24, y: 70, fontSize: 32, fontWeight: "700", color: "#000000", fontFamily: "Georgia, serif", maxWidth: 400 },
      { type: "text", id: "body", content: "Votre renouvellement approche. On s'en occupe.", x: 24, y: 120, fontSize: 16, fontWeight: "400", color: "#000000", fontFamily: "Inter, sans-serif" },
      { type: "cta", id: "cta", label: "Renouveler", x: 24, y: 158, bgColor: "#D11338", textColor: "#FFFFFF", borderRadius: 20, fontSize: 14, fontFamily: "Inter, sans-serif" },
    ],
  },
  {
    id: "bd-social-square",
    name: "Post social — Habitation",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#1A1A1A",
    layers: [
      { type: "logo", id: "logo", text: "belairdirect.", x: 60, y: 60, fontSize: 28, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "h1", content: "Ton chez-toi.\nBien protégé.", x: 60, y: 300, fontSize: 80, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 700, lineHeight: 1.1 },
      { type: "text", id: "body", content: "Assurance habitation à partir de 25$/mois.", x: 60, y: 620, fontSize: 32, fontWeight: "400", color: "rgba(255,255,255,0.7)", fontFamily: "'Roboto', sans-serif" },
      { type: "image", id: "mascot", placeholder: "🛡️ Chevalier relax", src: "/assets/knight/Sit_01.png", x: 600, y: 650, width: 400, height: 350 },
      { type: "cta", id: "cta", label: "Voir les offres", x: 60, y: 900, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 28, fontFamily: "'Montserrat', sans-serif" },
    ],
  },
];
