import { Template } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "bd-social-knight",
    name: "Post social — Groupe tes assurances",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Groupe tes\nassurances\net économise.", x: 65, y: 55, fontSize: 88, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 750, lineHeight: 1.02 },
      { type: "cta", id: "cta", label: "En savoir plus", x: 65, y: 470, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 24, fontSize: 24, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Petit Chevalier", src: "/assets/knight/Heart_01.png", x: 420, y: 420, width: 660, height: 660 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 65, y: 950, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 65, y: 995, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-story-maison",
    name: "Story — Première maison",
    brand: "belairdirect",
    format: "story",
    width: 1080,
    height: 1920,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Économisez\njusqu'à 300$\nsur votre\nassurance\nhabitation\navec\nbelairdirect.", x: 65, y: 80, fontSize: 88, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 960, lineHeight: 1.0 },
      { type: "cta", id: "cta", label: "En savoir plus", x: 65, y: 900, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 28, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier maison", src: "/assets/knight/Hold_House_01.png", x: 180, y: 1050, width: 780, height: 700 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 310, y: 1790, fontSize: 40, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 290, y: 1840, fontSize: 20, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-habitation",
    name: "Post social — Habitation",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Ton chez-toi.\nBien protégé.\nBien assuré.", x: 65, y: 55, fontSize: 84, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 750, lineHeight: 1.02 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 65, y: 440, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 24, fontSize: 24, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier assis", src: "/assets/knight/Sit_01.png", x: 400, y: 440, width: 680, height: 600 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 65, y: 950, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 65, y: 995, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-story-auto",
    name: "Story — Assurance auto",
    brand: "belairdirect",
    format: "story",
    width: 1080,
    height: 1920,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Ton assurance\nauto,\nsimplifiée.", x: 65, y: 160, fontSize: 100, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 960, lineHeight: 1.0 },
      { type: "text", id: "body", content: "Soumission en 5 min.\nZéro paperasse.", x: 65, y: 680, fontSize: 38, fontWeight: "400", color: "rgba(255,255,255,0.8)", fontFamily: "'Roboto', sans-serif", lineHeight: 1.4 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 65, y: 840, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 28, fontSize: 28, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier auto", src: "/assets/knight/Hold_Car_02_Car_And_House.png", x: 140, y: 1020, width: 820, height: 720 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 310, y: 1790, fontSize: 40, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 290, y: 1840, fontSize: 20, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-fier",
    name: "Post social — Économise 20%",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Économise\njusqu'à 20%\nsur ton\nassurance.", x: 65, y: 55, fontSize: 86, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 700, lineHeight: 1.02 },
      { type: "cta", id: "cta", label: "Obtenir ma soumission", x: 65, y: 470, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 24, fontSize: 24, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier fier", src: "/assets/knight/Proud_01.png", x: 420, y: 420, width: 660, height: 660 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 65, y: 950, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 65, y: 995, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
  {
    id: "bd-social-phone",
    name: "Post social — Mobile",
    brand: "belairdirect",
    format: "social",
    width: 1080,
    height: 1080,
    backgroundColor: "#C8102E",
    layers: [
      { type: "text", id: "h1", content: "Gère ton\nassurance\ndepuis\nton cell.", x: 65, y: 55, fontSize: 86, fontWeight: "800", color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif", maxWidth: 650, lineHeight: 1.02 },
      { type: "cta", id: "cta", label: "Télécharger l'app", x: 65, y: 470, bgColor: "#0F68D8", textColor: "#FFFFFF", borderRadius: 24, fontSize: 24, fontFamily: "'Montserrat', sans-serif", borderColor: "#FFFFFF", borderWidth: 2 },
      { type: "image", id: "mascot", placeholder: "Chevalier téléphone", src: "/assets/knight/Hold_Phone_01.png", x: 380, y: 380, width: 700, height: 700 },
      { type: "logo", id: "logo", text: "belairdirect.", x: 65, y: 950, fontSize: 36, color: "#FFFFFF", fontFamily: "'Montserrat', sans-serif" },
      { type: "text", id: "sub-logo", content: "assurances auto et habitation", x: 65, y: 995, fontSize: 18, fontWeight: "400", color: "rgba(255,255,255,0.6)", fontFamily: "'Roboto', sans-serif" },
    ],
  },
];
